name: DevOps Delivery Pipeline

on:
  push:
    branches: [ main, dev ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # יצירת תג דינמי (למשל dev-sha או main-sha)
          TAG="${{ github.ref_name }}-${{ github.sha }}"
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 2. יצירת קלאסטר בסיסי בעזרת Kind
      - name: Setup Kubernetes Cluster (Kind)
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: main-cluster

    
      - name: Install and Create vcluster
        run: |
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64"
          chmod +x vcluster
          sudo mv vcluster /usr/local/bin/
          
          # יצירת הקלאסטר הוירטואלי בתוך Kind
          vcluster create my-vcluster --connect=false
      
      - name: Deploy with Helm
        run: |
          helm dependency update ./my-app-chart
          helm install my-app ./my-app-chart \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }}
          
          echo "Waiting for MySQL to be ready..."
      - name: Validation Test
        run: |
          # פתיחת הפורט
          kubectl port-forward service/my-app 30001:80 & 
          
          echo "Waiting for application (and MySQL) to be ready..."
          ATTEMPTS=0
          MAX_ATTEMPTS=50 
          until curl -s http://localhost:30001 | grep "200 OK"; do
            echo "Waiting... ($ATTEMPTS/$MAX_ATTEMPTS)"
            kubectl get pods
            sleep 10
            ATTEMPTS=$((ATTEMPTS+1))
            if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
              echo "Timeout reached!"
              kubectl describe pod -l app.kubernetes.io/name=mysql
              exit 1
            fi
          done
          echo "Success! The app is alive!"